# Generated by Django 4.2.5 on 2024-03-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_custom_input_challenge_custom_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='custom_input',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='custom_output',
        ),
    ]
