# Generated by Django 4.2.5 on 2024-03-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_codinganswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodingAnswer',
        ),
    ]
